[project]
name = "tupleclass"
version = "0.0.1"
authors = [
  { name="Nicholas Ramsay", email="nickramsay15@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.12"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
